version: '3.5'

volumes:
  postgres:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
       - postgres:/var/lib/posgresql/data
    ports:
      - 5432:5432